#+TITLE: Computing Greatest Common Divisor of N polynomials
#+AUTHOR: lalo
#+STARTUP: indent
#+DATE: 2023-05-30
#+TAGS: programming math

Unfortunately, most of the time the math being programmed is limited by only numbers.  Plotting functions, computing some numbers, counting etc.  Symbolic computations are often avoided as they're thought hard for some reason.  In this article I'll show that's not true.  By using proper and expressive tools, such as functional programming, it is very easy to do computation with higher level mathematical objects like polynomials.

The problem that I'm solving here was my homework, except our teacher assumed that we're going to do all calculations by hand.  As a functional programming enthusiast I wanted to solve this problem using programming.  I used the [[https://ocaml.org][OCaml]] programming language.  I'm new to this language, so my code might look a bit dumb.  Also, most of the functions listed here can be [[https://en.wikipedia.org/wiki/Tail_call][tail call optimized]], but performance was the last thing I cared of.

* Introduction

Polynomials are mathematical objects that look like this: $f(x) = a_0 + a_1 x + \dots + a_n x^n$.  Here $a_0$, $a_1$, $\dots$ and $a_n$ are elements of a set that we'll be calling a set of *numbers*.  Those numbers can be anything: integers, rational numbers, real numbers, complex numbers, you name it .  The only restriction is that this set must be a [[https://en.wikipedia.org/wiki/Ring_(mathematics)][ring]] with commutative multiplication.  The number $n$ in polynomial is called the *degree* of polynomial.  It's usually written as $deg f$.

With these facts in mind, it is possible to define polynomial addition, subtraction, multiplication and even [[https://en.wikipedia.org/wiki/Polynomial_long_division][division]].  These operations are exactly the operations needed for [[https://en.wikipedia.org/wiki/Euclidean_algorithm][Euclidean algorithm]] to work.  Yes, Euclidean algorithm can work with anything! It just needs *objects*, that it's operating on, behave like numbers.

* Basic operations

Let's start with code.  I suggest to make functions for operations on numbers, so we'll be able to easily change the set that we're operating on.

#+begin_src tuareg
  let num_add a b = (a +. b)
  let num_sub a b = (a -. b)
  let num_mul a b = (a *. b)
  let num_div a b = (a /. b)
  let num_zero = 0.
#+end_src

Here we defined our operations working on float numbers.  It is also possible to make operations for [[https://en.wikipedia.org/wiki/Multiplicative_group_of_integers_modulo_n][group of integers modulo 7]]:

#+begin_src tuareg
  let (mod) x y = ((x mod y) + y) mod y
  let num_add a b = (a + b) mod 7
  let num_sub a b = (a - b) mod 7
  let num_mul a b = (a * b) mod 7
  let num_div a b = (a / b) mod 7
  let num_zero = 0
#+end_src

Obvisouly, you can make use of any type of "numbers".  As I said they just must be a ring with commutative multiplication.

In our code we will use polynomials as lists.  First element of polynomial will be $a_0$ and last one will be $a_n$.  Let's define simple operations on our polynomials.  Next two operations are so easy that I won't even elaborate on them:

#+begin_src tuareg
  let add_poly a b =
    List.map2 num_add a b

  let sub_poly a b =
    List.map2 num_sub a b
#+end_src

* Helper functions

We'd want to print our polynomials in nice way.  Here is a function that converts polynomial to string, skipping zeros:

#+begin_src tuareg
  let rec print_poly a i = match a with
    | [] -> ""
    | x :: t ->
       let s = if x == num_zero then ""
               else if i == 0 then Printf.sprintf "+%f" x
               else Printf.sprintf "+%fx^%d" x i
       in s ^ (print_poly t (i+1))
#+end_src

So, =print_poly [1; 2; 0; 3] 0= evaluates to =+1.000000+2.000000x^1+0.000000x^2+3.000000x^3=.  Note that each next function we'll write is tested using =print_poly= making sure nothing is wrong.

We'd want a function that returns a polynomial of degree $n$ filled with zeros.  Here it is:

#+begin_src tuareg
  let rec zeros = function
    | 0 -> []
    | n -> [num_zero] @ (zeros (n-1))
#+end_src

Unfortunately, I didn't find a function that drops last element of a list in OCaml's standard library.  It can be implemented like this:

#+begin_src tuareg
  let rec drop_last a =
    a |> List.rev |> List.tl |> List.rev
#+end_src

* Division

Okay, we're faced with a serious task.  I think, if we were using imperative language it'd be hard to solve our task.  We would write nested for loops with counters which most likely would lead to a bug.  With =OCaml= I wrote function for division first try.  It's 10 lines of code.  I think one great thing about functional programming is that it forces you to reuse code by using recursion.  This approach perfectly fits higher level math.  Anyway, here's code:

#+begin_src tuareg
  let rec div_poly a b =
    let d1 = deg_poly a in
    let d2 = deg_poly b in
    if d1 < d2 then ([], a)
    else
      let l1 = List.length a and l2 = List.length b in
      let g = (num_div (List.nth a (l1-1)) (List.nth b (l2-1))) in
      let c = mul_poly b g (d1-d2) in
      let ch, ost = (div_poly (drop_last (sub_poly a c)) b) in
      (ch @ [g], ost)
#+end_src

This function takes two polynomials and returns tuple consisting of =quotient= and =reminder= of division.

* Greatest Common Divisor

This is just a classic Euclidean algorithm, nothing special about it:

#+begin_src tuareg
  let rec gcd_poly a b =
    let d1 = deg_poly a in
    let d2 = deg_poly b in
    if d1 < d2 then gcd_poly b a
    else
      let q, r = div_poly a b in
      if r == [] then a
      else gcd_poly b r
#+end_src

If you're following this article coding yourself then don't be lazy and make some tests.  They will help a lot in understanding.

Having the =gcd_poly= function it's very easy to create a function that will compute *gcd* of N polynomials.  It's just gorgeous:

#+begin_src tuareg
  let rec gcd_poly_n = function
    | [] -> raise (Invalid_argument "error")
    | [a] -> a
    | h :: t -> gcd_poly h (gcd_poly_n t)
#+end_src

* Conclusion

The problem from my homework was to compute *gcd* of 3 polynomials: $f(x) = x^4 - 2 x^2 + 4$, $g(x) = x^4 - 4 x^2 + 4 x - 1$, $h(x) = x^4 - 4 x^2 + 4 x - 1$.  Those polynomials operated on group of integers modulo 7.  The result is $-3x + 1$.

It was a fun experience.  I'm starting to like functional programming more and more.  It may be not very suitable for some types of problems.  However, I think for solving mathematical problems it fits the best.
